# fly.toml app configuration file generated for threadshift-api on 2025-12-23T22:15:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'threadshift-api'
primary_region = 'iad'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'get'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
